### ISSUE TITLE
pointsAbove is not a good parameter name to refer to the position of the indicators

### ISSUE THREAD

**Issue by antonio-pedro99** [eliezerantonio/flutter_carousel_intro#16]
I know `points` might come from Portuguese, which literally means dots, but here it gives the feeling that we want to point something above something.

I think a good name for this parameter should be 
- `indicatorsAlignment`
- `indicatorsTop`

and more, what if instead of bool use enum to indicate the direction/Alignment of the indicators?
Something like 
enum DotsPosition { top, bottom }
or IndicatorsPostion { top, bottom }

**Comment by eliezerantonio** [comment]
sorted out
