### ISSUE TITLE
Error: Could not find the correct Provider<SliderModel> above this FlutterCarouselIntro Widget

### ISSUE THREAD

**Issue by antonio-nicolau** [eliezerantonio/flutter_carousel_intro#19]
Currently there's an issue where is necessary add ChangeNotifierProvider to the example project to be able to run the package locally while in development process.

I suggest to change Provider to Riverpod to avoid those kind of `Provider not found`exceptions

### How to reproduce:
1. Go to pubspec.yaml
2. Change `flutter_carousel_intro` to be loaded from local instead of pub.dev
3. Run the project

**Comment by eliezerantonio** [comment]
sorted out
