### ISSUE TITLE
Swipe the carousel to the current clicked indicator

### ISSUE THREAD

**Issue by antonio-nicolau** [eliezerantonio/flutter_carousel_intro#29]
Currently is only possible to slide the carousel by swipe the page, it brings a limitation: we cannot jump from last item to first one or first to third. We have a linear behaviour
Would be nice to also Swipe the carousel by click on indicators, this way we overcome this limitation

This way we would have two behaviour:
1.  Change the carousel position by Swiping
2. Change the carousel position by click on indicators

**Comment by antonio-nicolau** [comment]
Should be implemented here https://github.com/eliezerantonio/flutter_carousel_intro/pull/30

**Comment by eliezerantonio** [comment]
well done, you are the best
