### ISSUE TITLE
Add a better description

### ISSUE THREAD

**Issue by antonio-pedro99** [eliezerantonio/flutter_carousel_intro#4]
Hi @eliezerantonio 

You have done such an amazing package, congrats for making it.

It would be nice to have more details about the package here on Github and on pub.dev! 

Wishing you all the best!

**Comment by eliezerantonio** [comment]
Hi @antonio-pedro99 

Thanks for the corrections (your contribution) and sugestions

i will Add a better description  in both places (Github and pub.dev) in this weekend


thank you so much

**Comment by antonio-pedro99** [comment]
No problem!
